### ISSUE TITLE
rustfmt

### ISSUE THREAD

**Issue by parasyte** [meowitzher/sepax2d#4]
Hi! What are your opinions on formatting the code with rustfmt? I have to disable it in my IDE to make any contributions, or else my PRs will be unreadable with too many unrelated changes.

I won't debate the merits of code style consistency, but that's what's on the table. If it's a concern, rustfmt does have [some level of configuration](https://github.com/rust-lang/rustfmt/blob/master/Configurations.md). And there are other options to consider as well, like [EditorConfig](https://editorconfig.org/).

**Comment by meowitzher** [comment]
Sorry for the delay, I've moved on to other projects so I'm not really active here.

I have strong opinions about code formatting, but since I'm not actively maintaining this anymore, it'd be prudent for it to have some form formatting so that other contributors don't need to rip their hair out over my personal taste. I've formatted the code using the default settings.
